set CONDA_ENVIRO=pdal-build

del /s /q  %CONDA_ENVIRO%
mkdir %CONDA_ENVIRO%
pushd %CONDA_ENVIRO%

call conda activate %CONDA_ENVIRO%

echo "conda prefix" %CONDA_PREFIX%
REM set GENERATOR="Visual Studio 14 2015 Win64"
set GENERATOR="NMake Makefiles"
REM set GENERATOR="Ninja"

set ORACLE_HOME=%CONDA_PREFIX%
cmake -G %GENERATOR% ^
      -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo ^
      -DCMAKE_LIBRARY_PATH:FILEPATH="=%CONDA_PREFIX%/Library/lib" ^
      -DCMAKE_INCLUDE_PATH:FILEPATH="%CONDA_PREFIX%/Library/include" ^
      -DLIBLZMA_LIBRARY:FILEPATH=%CONDA_PREFIX%\Library\lib\liblzma.lib ^
      -DZSTD_LIBRARY:FILEPATH=%CONDA_PREFIX%\Library\lib\libzstd.lib ^
	  -DPython3_ROOT_DIR:FILEPATH="%CONDA_PREFIX%" ^
      -DBUILD_PLUGIN_PYTHON=OFF ^
      -DBUILD_PLUGIN_FBX=OFF ^
      -DBUILD_PLUGIN_PGPOINTCLOUD=OFF ^
      -DBUILD_PLUGIN_I3S=OFF ^
      -DBUILD_PLUGIN_E57=OFF ^
      -DBUILD_PLUGIN_SQLITE=OFF ^
      -DBUILD_PLUGIN_ICEBRIDGE=OFF ^
      -DBUILD_PLUGIN_NITF=OFF ^
      -DBUILD_PLUGIN_TILEDB=OFF ^
      -DWITH_TESTS=OFF ^
      -DWITH_ZLIB=OFF ^
      -DWITH_ZSTD=OFF ^
      -DWITH_LZMA=OFF ^
      -DBUILD_PGPOINTCLOUD_TESTS=OFF ^
      -DBUILD_SQLITE_TESTS=OFF ^
      -DBUILD_OCI_TESTS=OFF ^
      -DCMAKE_VERBOSE_MAKEFILE=OFF ^
      -DWITH_LAZPERF=OFF ^
      -DWITH_LASZIP=OFF ^
      .. --debug-trycompile

REM call ninja
nmake /f Makefile
